# Basic info
replicaCount: 1

image:
  repository: streamreactor/cassandra
  tag: 1.2.1.7
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

# Monitoring
monitoring:
  pipeline: "test-cassandra"
  enabled: true
  port: 9102
  path: "/metrics"

podManagementPolicy: OrderedReady

kafka:
  replicationFactor: 1
  bootstrapServers: 
    - name: kafka
      port: 9092
  image:
    repository: landoop/fast-data-dev
    tag: 2.0.0
    pullPolicy: IfNotPresent

schemaRegistries:
  enabled: true
  hosts:
    - host: kafka
      protocol: http
      port: 8081
      jmxPort: 9582 

secretsProvider: env

consistencyLevel: ""

# javaHeap options    
javaHeap: 256M

# clusterName The connect cluster name. This is the consumer group id for the backing topics
clusterName: "cassandra-test"

# restPort The rest port of Connect
restPort: "8083"

# logLevel The log4j level
logLevel: INFO

keySpace: "test"

# keyConverter The key converter to/from Connects struct
keyConverter: "io.confluent.connect.avro.AvroConverter"

# valueConverter The key converter to/from Connects struct
valueConverter: "io.confluent.connect.avro.AvroConverter"

# connectorClass
connectorClass: "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector"

# applicationId name of the connector
applicationId: "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector"

# topics to sink
topics: "cassandra-sink"

# kcql KCQL expression describing field selection and routes. type: STRING importance: HIGH
kcql: "INSERT INTO orders SELECT * FROM cassandra-sink"

# contact points
contactPoints: "cassandra"

# username Username to connect to Cassandra with. type: STRING importance: HIGH
username: "cassandra"

# password Password key for cassandra
password: "cassandra"

# mappingCollectionToJson Mapping columns with type Map, List and Set like json
mappingCollectionToJson: true