
{{- $name := .Chart.Name -}}
{{- $version := .Chart.Version -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- range .Values.services }}
kind: Endpoints
metadata:
  name: {{ .host }}
  labels:
    chart: "{{ $name }}-{{ $version}}"
    release: "{{ $releaseName }}"
    heritage: "{{ $releaseService }}"
subsets:
- addresses:
  {{- range .endpoints }}
  - ip: {{ . }}
  {{- end }}
  ports:
  {{- range .ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
  {{- end }}
---
{{- end }}

